[tools]
node = "24"
python = "latest"

[env]
MISE_GO_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-golang-packages"
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-npm-packages"
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-python-packages"

[settings]
idiomatic_version_file = true

# configure `mise install` to always keep the downloaded archive
# always_keep_download = false        # deleted after install by default
# always_keep_install = false         # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/code', '~/jellyfish'
]

verbose = false     # set to true to see full installation output, see `MISE_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr
yes = false         # set to true to automatically answer yes to all prompts

# delete this once the stupid warning stops showing up, pain in my butt. I
# don't care about idiomatic version support but I do care about not getting a
# giant warning every time I do somethi
# https://github.com/jdx/mise/discussions/4345
idiomatic_version_file_enable_tools = ["node"]

# not_found_auto_install = true # see MISE_NOT_FOUND_AUTO_INSTALL
# task_output = "prefix" # see Tasks Runner for more information
# paranoid = false       # see MISE_PARANOID

# shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `MISE_SHORTHANDS_FILE`
# disable_default_shorthands = false # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
# disable_tools = ['node']           # disable specific tools, generally used to turn off core tools
# 
# env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`
# 
# experimental = true # enable experimental features
# 
# # configure messages displayed when entering directories with config files
# status = {missing_tools = "if_other_versions_installed", show_env = false, show_tools = false}
